apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-

resources:
- nginx-configmap.yaml
- nginx-deployment.yaml 
- nginx-svc.yaml

commonAnnotations:
  channel: justopensource
